title: Demoscene.no
description: >-
  Demoscene.no is a website for the Norwegian demoscene community.
tagline: New and "improved" source code!
baseurl: ""
url: "http://demoscene.no"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 10

collections:
  articles:
    output: true

defaults:
  - scope:
      path: "_articles"
    values:
      layout: article
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: "assets/logos"
    values:
      logo: true
  - scope:
      path: "files"
    values:
      file: true

links:
  - title: pouet
    url: https://www.pouet.net/
  - title: scene.org
    url: https://www.scene.org/
  - title: quotes
    url: https://quotes.demoscene.no/
  - title: slengpung
    url: http://www.slengpung.com
